services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.2.0
    environment:
      # - http_proxy
      # - https_proxy
      - MEILI_MASTER_KEY=yxhEg72_4F3T4kM_nHEUaAjbDkPFB1xy2kMMZVmewYY
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - 7700:7700
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./data11.ms:/data.ms
    restart: unless-stopped

networks:
  front-tier:
    external: true
  back-tier:
    external: true
