services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - results:/usr/share/caddy/r
    networks:
      - front-tier

#  partners:
#    build: partners
#    sysctls:
#      - net.ipv4.ip_forward=1
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - "3000:3000"
#    devices:
#      - "/dev/net/tun:/dev/net/tun"
#    volumes:
#      - results:/app/r
#    environment:
#      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
#      - NODE_ENV=production
#      - DATABASE_URL=${PARTNERS_DB_URL}
#    networks:
#      - front-tier
#      - back-tier
#    depends_on:
#      - caddy
#      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    # Make sure log colors show up correctly
    tty: true
    networks:
      - back-tier

  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    networks:
      - back-tier

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - front-tier
  #     - back-tier

#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
#    networks:
#      - front-tier
#      - back-tier

  # vitalab.com.ua
  vitalab-core:
    build:
      context: ./shop/vitalab-core
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: vitalab-core
    depends_on:
      - db_core
      - redis
    environment:
      # DATABASE_URL: postgresql://postgres:R0hE9O9K2oP3BISB@db.fjkqqrmctfyqwgjdxiix.supabase.co:5432/postgres
      DATABASE_URL: ${VITALAB_CORE_DB_URL}
      REDIS_URL: redis://redis
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    networks:
      - front-tier
      - back-tier
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"

  vitalab-storefront:
    build:
      context: ./shop/vitalab-storefront
      dockerfile: Dockerfile
    container_name: vitalab-storefront
    depends_on:
      - caddy
    networks:
      - front-tier
      - back-tier
    ports:
      - "8000:8000"

  db_test:
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vitalab
      - POSTGRES_PASSWORD=Pb7aHebT23v5P5akC777
      - POSTGRES_DB=vitalabtest
    # Make sure log colors show up correctly
    tty: true
    networks:
      - front-tier
      - back-tier

  db_core:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - pgdata_core:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${VITALAB_CORE_DB_USER}
      - POSTGRES_PASSWORD=${VITALAB_CORE_DB_PASSWORD}
      - POSTGRES_DB=${VITALAB_CORE_DB}
    # Make sure log colors show up correctly
    tty: true
    networks:
      - front-tier
      - back-tier

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.30.5
    environment:
      # - http_proxy
      # - https_proxy
      - MEILI_MASTER_KEY=yxhEg72_4F3T4kM_nHEUaAjbDkPFB1xy2kMMZVmewYY
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - 7700:7700
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./data7.ms:/data.ms
    restart: unless-stopped

  vitalab-results:
    build:
      context: ./vl-results
      dockerfile: Dockerfile
    container_name: vitalab-results
    depends_on:
      - caddy
    networks:
      - front-tier
      - back-tier
    ports:
      - "3001:3001"

  vitalab-pay:
    build:
      context: ./vitalab-pay
      dockerfile: Dockerfile
    container_name: vitalab-pay
    depends_on:
      - caddy
    networks:
      - front-tier
      - back-tier
    ports:
      - "3002:3002"

  redis-dev:
    image: redis:latest
    expose:
      - "6380:6379"
    networks:
      - back-tier

volumes:
  pgdata:
  pgdata_test:
  pgdata_core:
  caddy_data:
  caddy_config:
  results:

networks:
  front-tier:
    external: true
  back-tier:
    external: true
